from __future__ import annotations
from typing import Protocol, Optional, Tuple

class DHTNetwork(Protocol):
    def build(self, n_nodes: int, seed: int = 0) -> None: ...
    def insert(self, key: str, value: dict) -> int: ...
    def lookup(self, key: str) -> Tuple[Optional[dict], int]: ...
    def update(self, key: str, value: dict) -> int: ...
    def delete(self, key: str) -> int: ...
    def join(self) -> int: ...
    def leave(self, node_id=None) -> int: ...
